
package com.gdc.robothelper.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
//@WebServiceClient(name = "SisproRobotManagerHelperService", targetNamespace = "http://webservice.samyg.gdc.com/", wsdlLocation = "http://samyg2pp.sispro.mx:8080/helper/SRMHelper?wsdl")

@WebServiceClient(name = "SisproRobotManagerHelperService", targetNamespace = "http://webservice.samyg.gdc.com/", wsdlLocation = "http://samyg2.sispro.mx:8080/helper/SRMHelper?wsdl")
//@WebServiceClient(name = "SisproRobotManagerHelperService", targetNamespace = "http://webservice.samyg.gdc.com/", wsdlLocation = "http://samyg2test.sispro.mx:8080/helper/SRMHelper?wsdl")

public class SisproRobotManagerHelperService
    extends Service
{

    private final static URL SISPROROBOTMANAGERHELPERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SISPROROBOTMANAGERHELPERSERVICE_EXCEPTION;
    private final static QName SISPROROBOTMANAGERHELPERSERVICE_QNAME = new QName("http://webservice.samyg.gdc.com/", "SisproRobotManagerHelperService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
//            url = new URL("http://samyg2.sispro.mx:8080/helper/SRMHelper?wsdl");
            url = new URL("http://samyg2pp.sispro.mx:8080/helper/SRMHelper?wsdl");


//            url = new URL("http://samyg2test.sispro.mx:8080/helper/SRMHelper?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SISPROROBOTMANAGERHELPERSERVICE_WSDL_LOCATION = url;
        SISPROROBOTMANAGERHELPERSERVICE_EXCEPTION = e;
    }

    public SisproRobotManagerHelperService() {
        super(__getWsdlLocation(), SISPROROBOTMANAGERHELPERSERVICE_QNAME);
    }

    public SisproRobotManagerHelperService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SISPROROBOTMANAGERHELPERSERVICE_QNAME, features);
    }

    public SisproRobotManagerHelperService(URL wsdlLocation) {
        super(wsdlLocation, SISPROROBOTMANAGERHELPERSERVICE_QNAME);
    }

    public SisproRobotManagerHelperService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SISPROROBOTMANAGERHELPERSERVICE_QNAME, features);
    }

    public SisproRobotManagerHelperService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SisproRobotManagerHelperService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SisproRobotManagerHelper
     */
    @WebEndpoint(name = "SisproRobotManagerHelperPort")
    public SisproRobotManagerHelper getSisproRobotManagerHelperPort() {
        return super.getPort(new QName("http://webservice.samyg.gdc.com/", "SisproRobotManagerHelperPort"), SisproRobotManagerHelper.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SisproRobotManagerHelper
     */
    @WebEndpoint(name = "SisproRobotManagerHelperPort")
    public SisproRobotManagerHelper getSisproRobotManagerHelperPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.samyg.gdc.com/", "SisproRobotManagerHelperPort"), SisproRobotManagerHelper.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SISPROROBOTMANAGERHELPERSERVICE_EXCEPTION!= null) {
            throw SISPROROBOTMANAGERHELPERSERVICE_EXCEPTION;
        }
        return SISPROROBOTMANAGERHELPERSERVICE_WSDL_LOCATION;
    }
    
    
    public static URL getUrl(){
    	return SISPROROBOTMANAGERHELPERSERVICE_WSDL_LOCATION;
    }

}
